spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: false
      settings:
        trace: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true