spring:
  datasource:
    url: jdbc:h2:mem:moviedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true